### ISSUE TITLE
Not finding connection tree

### ISSUE THREAD

**Issue by trevorgrout** [erpas/rivergis#2]
Upon initially installing rivergis I was able to see the connection tree.  I pushed the "x" and it disappeared.  Now when I try to open the rivergis plugin I cannot get it to show.  I have tried uninstalling everything and re-install but I cannot seem to get that connection tree to show.  I don't know how to let rivergis know my schema/database connections.

Any suggestions?

Trevor

I am really excited to play around with this plugin but I need to get it to work first.

![rivergis](https://cloud.githubusercontent.com/assets/11817864/7276531/c5258d02-e8cf-11e4-868d-31d30e750b6b.JPG)

**Comment by erpas** [comment]
Right-click to the right of the Help text menu and turn the Connections
panel on.
Let me know if that worked for you.

Greetings,

Radek

2015-04-22 16:13 GMT+02:00 trevorgrout <notifications@github.com>:

> Upon initially installing rivergis I was able to see the connection tree.
> I pushed the "x" and it disappeared. Now when I try to open the rivergis
> plugin I cannot get it to show. I have tried uninstalling everything and
> re-install but I cannot seem to get that connection tree to show. I don't
> know how to let rivergis know my schema/database connections.
>
> Any suggestions?
>
> Trevor
>
> I am really excited to play around with this plugin but I need to get it
> to work first.
>
> [image: rivergis]
> <https://cloud.githubusercontent.com/assets/11817864/7276531/c5258d02-e8cf-11e4-868d-31d30e750b6b.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erpas/rivergis/issues/2>.
>



-- 
Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html

**Comment by trevorgrout** [comment]
Well that was stupid simple.
Awesome, I see the connection tree now!!!
Thanks a ton!!
I am going to close this now.
