### ISSUE TITLE
Mesh Points not correctly importing into HEC-RAS

### ISSUE THREAD

**Issue by trevorgrout** [erpas/rivergis#3]
I am trying to generate a mesh using rivergis, however what I see in QGIS is not translated to HEC-RAS. The "mesh_pts" layer has points that appear to be correctly placed (1st picture).  However, there appear to be missing points in the HEC-RAS geometry file (2nd picture).

Here is a link to the model files, and shapefiles used to create this issue:
https://www.dropbox.com/sh/zeecjdegqs7phnr/AAD-4xor0s4-zFWSFlwl6Dkua?dl=0

![rivergis_meshpts](https://cloud.githubusercontent.com/assets/11817864/7286758/f9ca84ec-e913-11e4-88f3-12cc7494de3f.JPG)

![rivergis_hecrasgeometry](https://cloud.githubusercontent.com/assets/11817864/7286772/0c1cd60e-e914-11e4-9d9a-202e7c7989ab.JPG)

**Comment by erpas** [comment]
Seems that you have selected single river reach --- it is visible as yellow on the first picture. Try to deselect all features in QGIS before running RiverGIS. Hope that will help.
Also please let me know if you're running the plugin from QGIS official repository or the latest github version.

Thanks,

Radek

**Comment by trevorgrout** [comment]
Unfortunately, I repeated my process with the same result.  A quick look at the "mesh_pts" layer reveals there are 26,734 points whereas the HEC-RAS Geometry file says there are 25,643 points.  As we can see from the pictures in my previous post, the rivergis tool produced the points for all the rivers, however, they don't seem to have transferred to the geometry file.  I got my version from the repository and it seems to be the latest version.

**Comment by erpas** [comment]
Rivergis tries to figure out which riverline belongs to which 2d area
automatically. A riverline must be INSIDE a 2d area to be processed. Try to
move last vertices of your riverlines so they are within your area. That
should help for now.

I will try to use another kind of check in the next RiverGIS version. Thank
you for bringing this out!

Best regards,

Radek

2015-04-23 15:33 GMT+02:00 trevorgrout <notifications@github.com>:

> Unfortunately, I repeated my process with the same result. A quick look at
> the "mesh_pts" layer reveals there are 26,734 points whereas the HEC-RAS
> Geometry file says there are 25,643 points. As we can see from the pictures
> in my previous post, the rivergis tool produced the points for all the
> rivers, however, they don't seem to have transferred to the geometry file.
> I got my version from the repository and it seems to be the latest version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erpas/rivergis/issues/3#issuecomment-95586244>.
>



-- 
Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html

**Comment by trevorgrout** [comment]
Thank you so much!  This is a really impressive tool and your suggestion solved my problem. I used ArcMAP to clip the line features to the polygon.  I went ahead and trimmed them to where they were entirely inside of the polygon and presto!!! it worked!!!
Thanks again!
