### ISSUE TITLE
9 Sided polygons created by RiverGIS

### ISSUE THREAD

**Issue by trevorgrout** [erpas/rivergis#4]
The new Version of HEC-RAS 5.0 requires that polygons have no more than 8 sides.  I noticed that the mesh that was generated by RiverGIS had a handful of polygons that contain 9 sides.  While this only happened to about 10 cells out of 100,000 cells, and I was able to correct them fairly easily, it will prevent HEC-RAS from running.
Please see example pictures below:
![rivergis-hecraserror](https://cloud.githubusercontent.com/assets/11817864/7305505/ed9c5802-e9c3-11e4-8fcf-fbde6722d602.JPG)
![rivergis 9 sides](https://cloud.githubusercontent.com/assets/11817864/7305510/f45b2b78-e9c3-11e4-86a2-a5164b71e497.JPG)

**Comment by erpas** [comment]
I am aware of that limitation. Unfortunatelly, the mesh is not generated by RiverGIS --- it is created based on the points locations by HEC-RAS. 
I hope the limitation will be removed in the upcoming official release of HEC-RAS 5.0.
If not, I will put additional checks in RiverGIS to prevent more that 8 faces in the cells.
Thank you for reporting this problem!
