### ISSUE TITLE
Cell Spacing and consistency

### ISSUE THREAD

**Issue by trevorgrout** [erpas/rivergis#5]
Upon generating cells for various structures I am finding that in some cases the horizontal spacing varies dramatically for structures that are set to the same cell size and meshrows. The examples provided have 2D area with a cellsize of 75' and note how the structure is depicted. One has very dense, narrow cells while the other has them more spread out.  What is causing this?  This is making the 2D area contain polygons with far more than 8 sides.  The Cellsize and meshrows for the structures for these examples is the same (cellsize = 25', and meshrows = 1).

![rivergis_cellsize25rows1](https://cloud.githubusercontent.com/assets/11817864/7324935/4bbc7ad6-ea80-11e4-891f-03f452f57a13.JPG)
![rivergis_cellsize25rows1_big](https://cloud.githubusercontent.com/assets/11817864/7324946/6b255c4e-ea80-11e4-9449-0f7a697c430a.JPG)

**Comment by erpas** [comment]
Thanks for reporting. This is unusual. Can you upload somewhere the source
shapefiles? It is hard to say anything without them.

Radek

**Comment by trevorgrout** [comment]
Here is a link to my dropbox folder:
https://www.dropbox.com/sh/vzbkrjavam2fmfv/AADojtjmBQaXIJmKCxjF5bPXa?dl=0
I included the output geometry file as well.
I encountered this doing many different scenarios but these files should produce the problem.
![rivergis_issue](https://cloud.githubusercontent.com/assets/11817864/7327397/73e9a7a6-ea92-11e4-9d19-cfc9447b7819.JPG)

**Comment by erpas** [comment]
Thank you for reporting the problem.
I am not able to reproduce the error with the uploaded data. Whatever I do, the mesh is fine. Do you get the error every time the Create 2d Mesh Area is used or is it occasional problem?

I noticed your riverline has some sharp corners and that results in overlapping mesh points in 2nd and 3rd regular mesh rows. You can avoid that by smoothing your riverline (see picture) or lessening mesh rows number when the river is very curvy.

![smooth_riverline](https://cloud.githubusercontent.com/assets/3106699/7332453/292385da-eb40-11e4-8b3e-8916b35ea510.png)

**Comment by trevorgrout** [comment]
erpas,
I apologize profusely, I cannot seem to replicate this behavior.  I have been out of town so I have not had a chance to look into this till today.  I re-ran this again, and the cell spacing works much better.
There did not seem to be a consistent pattern to the problem I was having, and I will play around with it to see if I can replicate the behavior that I was getting. I wonder if it was a problem with the computer I was using or some setting I had. Could there be issues if we have too many schema in a database?  I will do a better job of QA/QC next time.

FYI, there is a new Beta version of HEC-RAS that was released to approved Beta testers dated 2015-03-22, when running the tool and importing into this version I get this:
![rivergis_beta](https://cloud.githubusercontent.com/assets/11817864/7415858/0450c134-ef21-11e4-9737-726ce3b162e0.JPG)
And here is a zoom in.
![rivergis_betazoom](https://cloud.githubusercontent.com/assets/11817864/7415863/094ec456-ef21-11e4-83c1-c9cd88b6b9fc.JPG)

I have not had a chance to delve into this too much and this may be because I have not smoothed my line out yet.  It does appear that the new version of RAS 5.0 Beta has some new checks (note the error:  "Mesh: 'CedarMesh': 1092 near-duplicate point(s) detected" in the pictures above).
So this is more an FYI update. I have not found a way to make the polygons appear in the new Version of RAS and I wonder if the error message at the bottom of the screen has something to do with this.  I will look into this further when I get a chance.
Trevor

**Comment by erpas** [comment]
Thanks for sharing your observations!

I think the number of PostgreSQL schemas shouldn't influence the tool. 
It seems the new beta (2015-03-22) brings some changes in the way the mesh is read and stored in HEC-RAS. Unfortunatelly, I am still on 2010-10-01 beta release.

I wonder if the fresh version has the breaklines feature already described by Chris Goodell on his blog [1] - maybe that could be helpful for you before I am able to look into the new mesh storing changes and make the right adjustments in the RiverGIS code.

Best regards,

Radek

[1] http://hecrasmodel.blogspot.com/2015/04/2d-mesh-leaking-part-2-2d-area.html

**Comment by trevorgrout** [comment]
Yes, I am able to create breaklines in the version I have. I am using it in the short term. However, your tool is nice because it allows me to take an existing shapefile of my structures/river and treat them as breaklines with differing cell sizes instead of having to manually trace them out. However, I sense you are suspending further development until the new version of ras comes out?  I don't blame you either.
Thanks
Trevor
